# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registered',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
