# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160213_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registered',
            new_name='registeredclass',
        ),
    ]
