# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20160214_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredclass',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='pincode',
            field=models.CharField(max_length=20),
        ),
    ]
