# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160214_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredclass',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='mobile',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='pincode',
            field=models.PositiveSmallIntegerField(max_length=20),
        ),
    ]
