# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20160214_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredclass',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=254, unique=True),
        ),
    ]
