# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20160214_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredclass',
            name='branch',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='pincode',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
