# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20160214_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredclass',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='mobile',
            field=models.PositiveSmallIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='pincode',
            field=models.PositiveSmallIntegerField(max_length=6),
        ),
    ]
