# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20160222_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredclass',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
