# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20160222_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredclass',
            name='dob',
            field=models.CharField(default=datetime.datetime(2016, 3, 10, 17, 4, 0, 389891, tzinfo=utc), max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredclass',
            name='fathername',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredclass',
            name='password',
            field=models.CharField(default='12', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredclass',
            name='photo',
            field=models.ImageField(default='a', upload_to=b''),
            preserve_default=False,
        ),
    ]
