# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20160310_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredclass',
            name='photo',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='rollno',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
