# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20160311_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredclass',
            name='photo',
            field=models.ImageField(upload_to=b''),
        ),
    ]
