# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20160313_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredclass',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registeredclass',
            name='password',
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='rollno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
