# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0017_auto_20160314_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredclass',
            name='rollno',
        ),
        migrations.AddField(
            model_name='registeredclass',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
