# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_feeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeid', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='feeinfo',
            old_name='year',
            new_name='year_sem',
        ),
        migrations.RemoveField(
            model_name='feeinfo',
            name='even',
        ),
        migrations.RemoveField(
            model_name='feeinfo',
            name='odd',
        ),
    ]
