# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_feeinfo_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostel_fee_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeid', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hostel_fee_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=10)),
                ('fee', models.IntegerField(default=0)),
            ],
        ),
    ]
