# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_hostel_fee_detail_hostel_fee_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='library_due',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('due', models.IntegerField()),
            ],
        ),
    ]
