# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_remove_library_due_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredclass',
            name='mobile',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registeredclass',
            name='pincode',
            field=models.CharField(max_length=30),
        ),
    ]
