# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_auto_20160323_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('subjects', models.TextField()),
                ('lectures', models.IntegerField()),
                ('tutorials', models.IntegerField()),
                ('practicals', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.feeinfo')),
            ],
        ),
    ]
