# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='lectures',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='practicals',
            new_name='practical',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='subjects',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='tutorials',
            new_name='tutorial',
        ),
    ]
