# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_auto_20160402_0812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subjects',
            new_name='subjects_detail',
        ),
    ]
