# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_auto_20160402_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects_detail',
            old_name='lecture',
            new_name='lectures',
        ),
        migrations.RenameField(
            model_name='subjects_detail',
            old_name='practical',
            new_name='practicals',
        ),
        migrations.RenameField(
            model_name='subjects_detail',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.RenameField(
            model_name='subjects_detail',
            old_name='tutorial',
            new_name='tutorials',
        ),
    ]
