# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0029_auto_20160402_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredclass',
            name='books',
        ),
        migrations.AddField(
            model_name='library_due',
            name='books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='library_due',
            name='flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='library_due',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='library_due',
            name='due',
            field=models.IntegerField(default=0),
        ),
    ]
