# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0033_remove_hostel_fee_detail_feeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetail',
            name='time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
