# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0034_feedetail_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel_fee_detail',
            name='time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
