# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0035_hostel_fee_detail_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(max_length=16)),
                ('month', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=12)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='subjects_detail',
            name='branch',
            field=models.CharField(max_length=50),
        ),
    ]
