# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0036_auto_20160406_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetail',
            name='flag',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
