# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0037_feedetail_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetail',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
